# Generated by Django 3.1.3 on 2021-05-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eprotocol', '0003_refecencecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eprotocolprojectinfo',
            name='code',
            field=models.CharField(error_messages={'unique': 'This code id already existed.'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='eprotocolprojectinfo',
            name='name',
            field=models.CharField(error_messages={'unique': 'This name id already existed.'}, max_length=1024, unique=True),
        ),
    ]
